version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-binance-notification}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
  app:
    image: romanhajek/binance-notification:latest
    restart: always
    depends_on:
      - "db"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-binance-notification}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-binance-notification}
      SLACK_TOKEN: ${SLACK_TOKEN:-***}
      SLACK_CHANNEL_ID: ${SLACK_CHANNEL_ID:-***}
volumes:
  data:
