version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-binance-notification}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
volumes:
  data:
